from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "crawler.db"

DEFAULT_MAX_WORKERS = 4
DEFAULT_FRONTIER_MAXSIZE = 1000
DEFAULT_FETCH_TIMEOUT_SECONDS = 10
DEFAULT_RATE_LIMIT_SECONDS = 0.2
DEFAULT_FRONTIER_GET_TIMEOUT_SECONDS = 1.0